import Head from 'next/head'
import styles from './../../styles/Home.module.css';
import Image from 'next/image';
import Link from "next/link"
import { FaRegEnvelope} from "react-icons/fa";
import { MdLockOutline} from "react-icons/md";
import { SiHappycow } from "react-icons/si";
import navBar from "../NavBar/NavBar";

export default function Layout({children}){
    return (
        <div className="flex flex-col items-center justify-center min-h-screen py-2">
            <Head>
                <title>RE-Source</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <navBar /> */}
            <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                <div className="bg-white rounded-2xl shadow-2xl flex w-2/3 max-w-4xl">
                
                {
                    children
                } 
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
                >
                Powered by Team Hlib <SiHappycow />
                </a>
            </footer>
        </div>

    )
}